[package]
name = "aoc21"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
geo = "0.18.0"
petgraph = "0.6.0"

[profile.release]
lto = "fat"
codegen-units = 1
